### PR TITLE
Support for listMembership API calls

### PR DESCRIPTION
**Pull request by hvt**

### CODE REVIEW

**Comment by hglattergotz** [comment]
@hvt Thanks for contributing the map entry!

**Comment by hglattergotz** [comment]
@hvt Do you need the new change released as a tagged version for your build process or are you fine with just installing from master?

**Comment by hvt** [comment]
@hglattergotz a new tagged version would be nice for me, but if that's too much of a hazzle, I'll happily use master :)

**Comment by hglattergotz** [comment]
@hvt Created v1.0.3

Thanks!

**Comment by hvt** [comment]
Thank you for the library, it's simple and elegant :]. (And thanks for the tag ;])

**Pull request merged**
